name: Oil Spill Intelligence V2

on:
  workflow_dispatch:

  schedule:
    # تشغيل كل 6 ساعات
    - cron: "0 */6 * * *"


jobs:

  oil-spill-monitor:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install Dependencies
        run: |
          pip install -r requirements.txt


      - name: Run Oil Spill Intelligence
        env:

          # Copernicus Sentinel-1
          CDSE_CLIENT_ID: ${{ secrets.CDSE_CLIENT_ID }}
          CDSE_CLIENT_SECRET: ${{ secrets.CDSE_CLIENT_SECRET }}

          # AIS Stream
          AISSTREAM_API_KEY: ${{ secrets.AISSTREAM_API_KEY }}

        run: |
          python main.py
