name: AISStream Test

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"


jobs:

  ais-test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install Dependencies
        run: |
          pip install websockets


      - name: Run AIS Test
        env:
          AISSTREAM_API_KEY: ${{ secrets.AISSTREAM_API_KEY }}

        run: |
          python ais_test.py
